title: "Serendipia"
description: "Proyecto Serendipia"
collections:
  ediciones:
    output: true
  recomendaciones:
    output: true

collections:
  ediciones:
    output: true
  recomendaciones:
    output: false
  videos:
    output: false
  trescosas:
    output: false
